<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<!-- 继承父模块的核心配置 -->
	<parent>
		<groupId>cn.edu.hnu</groupId>
		<artifactId>ArtifactLLM_banker</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<!--  relativePath：父模块 pom.xml 相对于当前子模块 pom.xml 的路径 -->
		<!-- 因为父模块 pom 在 ArtifactLLM_banker/pom.xml，子模块在 ArtifactLLM_banker/artifact-ai/pom.xml，所以路径是 ../pom.xml -->
		<relativePath>../pom.xml</relativePath>
	</parent>
	<packaging>jar</packaging><!--子模块打包方式-->
	<artifactId>artifact-knowledge</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>artifact-knowledge</name>
	<description>artifact-knowledge</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>
	<properties>
		<java.version>21</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-neo4j</artifactId>
		</dependency>
		<dependency>
			<groupId>cn.edu.hnu</groupId>
			<artifactId>artifact-common</artifactId>
		</dependency>
		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>fastjson</artifactId>
		</dependency>
	</dependencies>



</project>
